# Exercício 10: Dia da semana
# Use match-case para imprimir o dia correspondente
dia = int(input("Digite um número de 1 a 7: "))

match dia:
    case 1:
        ...
    case 2:
        ...
    case 3:
        ...
    case 4:
        ...
    case 5:
        ...
    case 6:
        ...
    case 7:
        ...
    case _:
        print("Dia inválido")
